version: build.{build}
image: Visual Studio 2017
environment:
  AzureAuthKey:
    secure: 4FuAR/X6tZkLQOE8SBvQnxMIPvmjESSTd7b/SaCtjsoWiw/ai0j6rNSppORzOqgIawCvs0pIeD13ZQlKsRwyOO0HZffj1l6FEyA2juaqKwsONlY7fkLH7XKPmu5+iT/k
init:
- cmd: git config --global core.autocrlf true
install:
# The Gremlin API is not supported on the emulator. The only way to use Gremlin and CosmosDb is to use the real service
#- ps: Start-FileDownload 'https://aka.ms/cosmosdb-emulator' -FileName 'c:\projects\cosmos-db.msi'
#- cmd: cmd /c start /wait msiexec /i "c:\projects\cosmos-db.msi" /qn /quiet /norestart /log install.log  
#- ps: Start-Process "start-emulator.cmd"
#- ps: .\wait-connect-cosmosdb.ps1

# Install the Tinkerpop-server
- ps: .\install-tinkerpop-server.ps1
before_build:
- cmd: >-
    gitversion /l console /output buildserver /updateAssemblyInfo

    nuget restore
build:
  verbosity: minimal
after_build:
- ps: >-
    $nuget_version = "$env:GitVersion_NuGetVersionV2"

    .\.packages\package-NBi-Gremlin.ps1 $nuget_version

test_script:
- ps: .\testing-override-azure-cosmosdb-connectionString.ps1 $env:AzureAuthKey
- ps: nunit-console-x86 NBi.Testing.Core.Gremlin\bin\debug\NBi.Testing.Core.Gremlin.dll /run:NBi.Testing.Core.Gremlin.Unit /result=result.unit.xml
- ps: nunit-console-x86 NBi.Testing.Core.Gremlin\bin\debug\NBi.Testing.Core.Gremlin.dll /run:NBi.Testing.Core.Gremlin.Acceptance,NBi.Testing.Core.Gremlin.Integration /result=result.azure.xml
- ps: .\testing-upload-result.ps1 'azure'
- ps: .\testing-override-tinkerpop-server-connectionString.ps1
- ps: nunit-console-x86 NBi.Testing.Core.Gremlin\bin\debug\NBi.Testing.Core.Gremlin.dll /run:NBi.Testing.Core.Gremlin.Acceptance,NBi.Testing.Core.Gremlin.Integration /result=result.tinkerpop.xml
- ps: .\testing-upload-result.ps1 'tinkerpop'
artifacts:
- path: NBi.Core.Gremlin\bin\Debug
  name: NBi.Gremlin
- path: .nupkg\NBi.Gremlin.*.nupkg
  name: NBi.Gremlin
deploy:
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    branch: /^(develop|release\/.+)$/
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://www.myget.org/F/nbi-gremlin/api/v2/package
  api_key:
    secure: +E89GuWTCkM1DpiRGoO3oRLIvLIjb8aPsHqNvga0ID/xdUx0cvDjI7XVdF12rmEm
  on:
    branch: develop