version: build.{build}
image: Visual Studio 2017
environment:
  AzureAuthKey:
    secure: 4FuAR/X6tZkLQOE8SBvQnxMIPvmjESSTd7b/SaCtjsoWiw/ai0j6rNSppORzOqgIawCvs0pIeD13ZQlKsRwyOO0HZffj1l6FEyA2juaqKwsONlY7fkLH7XKPmu5+iT/k
init:
- cmd: git config --global core.autocrlf true
#install:
# The Gremlin API is not supported on the emulator. The only way to use GRemlin and CosmosDb is to use the real service
#- ps: Start-FileDownload 'https://aka.ms/cosmosdb-emulator' -FileName 'c:\projects\cosmos-db.msi'
#- cmd: cmd /c start /wait msiexec /i "c:\projects\cosmos-db.msi" /qn /quiet /norestart /log install.log  
#- ps: Start-Process "start-emulator.cmd"
#- ps: .\wait-connect-cosmosdb.ps1
before_build:
- cmd: >-
    gitversion /l console /output buildserver /updateAssemblyInfo

    nuget restore
build:
  verbosity: minimal
after_build:
- ps: >-
    $nuget_version = "$env:GitVersion_NuGetVersionV2"

    .\.packages\package-NBi-Gremlin.ps1 $nuget_version

    .\testing-override-connectionString.ps1 $env:AzureAuthKey
test_script:
- cmd: nunit-console-x86 NBi.Testing.Core.Gremlin\bin\debug\NBi.Testing.Core.Gremlin.dll
artifacts:
- path: NBi.Core.Gremlin\bin\Debug
  name: NBi.Gremlin
- path: .nupkg\NBi.Gremlin.*.nupkg
  name: NBi.Gremlin
deploy:
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    branch: develop
- provider: NuGet
  api_key:
    secure: 7LDAnpfRuEmLf/4hhERYnfy3tHLBqC7wqScUEviYVYkNvrM7C3NN0h73se3QuoNh
  on:
    APPVEYOR_REPO_TAG: true
- provider: NuGet
  server: https://www.myget.org/F/nbi-gremlin/api/v2/package
  api_key:
    secure: +E89GuWTCkM1DpiRGoO3oRLIvLIjb8aPsHqNvga0ID/xdUx0cvDjI7XVdF12rmEm
  on:
    branch: develop